project:
  type: website
  output-dir: docs # render directory

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: flaty
    css: styles.css



